// tools/generateChecks.ts
// 获取developers-animatesdk-docs-master下的子文件夹，类似actionsPanel_object这样的
// 在types文件夹下，生成类似actionsPanel/actionsPanel.d.ts文件
// developers-animatesdk-docs-master在父目录


// tools/generateChecks.ts
import * as fs from 'fs';
import * as path from 'path';

// 配置路径
const DOCS_ROOT = path.resolve(__dirname, '../developers-animatesdk-docs-master');
const TYPES_OUTPUT_DIR = path.resolve(__dirname, '../types');

// 确保输出目录存在
if (!fs.existsSync(TYPES_OUTPUT_DIR)) {
    fs.mkdirSync(TYPES_OUTPUT_DIR, { recursive: true });
}

// 读取 docs 根目录下的一级子文件夹
const entries = fs.readdirSync(DOCS_ROOT, { withFileTypes: true });
const subDirs = entries
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name)
    .filter(name => name.endsWith('_object')); // 只处理以 _object 结尾的

console.log(`Found ${subDirs.length} _object folders:`);
subDirs.forEach(dir => console.log(` - ${dir}`));

// 为每个子文件夹生成 .d.ts 文件
for (const dir of subDirs) {
    // 例如 actionsPanel_object → actionsPanel
    const moduleName = dir.replace(/_object$/, '');

    const outputDir = path.join(TYPES_OUTPUT_DIR, moduleName);
    const outputFile = path.join(outputDir, `${moduleName}.d.ts`);

    // 确保输出子目录存在
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // 生成简单的声明内容（你可以根据需要扩展）
    const content = `// Auto-generated by generateChecks.ts
declare module '${moduleName}' {
  // TODO: Add actual type definitions based on documentation
  export = any;
}
`;


    fs.writeFileSync(outputFile, content.trim() + '\n', 'utf-8');
    console.log(`Generated: ${outputFile}`);
}

console.log('✅ All .d.ts files generated.');