// Generated by CoffeeScript 1.12.7
(function() {
  var n, numbers, squares;

  numbers = [1, 2, 3, 4];

  squares = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = numbers.length; i < len; i++) {
      n = numbers[i];
      if (n % 2 === 0) {
        results.push(n * n);
      }
    }
    return results;
  })();

  exports.squares = squares;

}).call(this);

//# sourceMappingURL=squares.js.map
